version: '3.9'
services:
  devcontainer:
    build:
      context: .
      dockerfile: dockerfile
    container_name: Laravel_Developer
    restart: unless-stopped
    command: sleep infinity
    volumes:
      - ../../:/workspaces:cached
